apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lamps-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest #1.21.6 / 1.22.1 / latest
        imagePullPolicy: Always #이미지를 항상 새롭게 pull 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: lamps-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx    #pod 라벨명